#!/bin/bash -x

WORKLOADS="/home/geedo/ec700/SWFloads/ShortTraces"
OUTPUT_DIR="/home/geedo/ec700/simware/data_task2"
LOG_INTERVAL=10000

mkdir -p data_task2/{SDSC,LLNL,NASA,LANL}

for DVFS in {100,95}
do
	echo "LANL with DVFS ${DVFS}"
	date
	./SimWare ${WORKLOADS}/LANL-O2K-short.swf -NUMBER_OF_CORES_IN_ONE_SERVER 4 -NUMBER_OF_SERVERS_IN_ONE_CHASSIS 8 -PERIODIC_LOG_INTERVAL ${LOG_INTERVAL} -SCHEDULING_ALGORITHM best_edp -DVFS_SETTING ${DVFS} 1> ${OUTPUT_DIR}/LANL/${DVFS}.o 2> ${OUTPUT_DIR}/LANL/${DVFS}.e
	echo "NASA with DVFS ${DVFS}"
	date
	./SimWare ${WORKLOADS}/NASA-iPSC-short.swf -NUMBER_OF_CORES_IN_ONE_SERVER 1 -NUMBER_OF_SERVERS_IN_ONE_CHASSIS 2 -PERIODIC_LOG_INTERVAL ${LOG_INTERVAL} -SCHEDULING_ALGORITHM best_edp -DVFS_SETTING ${DVFS} 1> ${OUTPUT_DIR}/NASA/${DVFS}.o 2> ${OUTPUT_DIR}/NASA/${DVFS}.e
	echo "LLNL with DVFS ${DVFS}"
	date
	./SimWare ${WORKLOADS}/LLNL-T3D-short.swf -NUMBER_OF_CORES_IN_ONE_SERVER 1 -NUMBER_OF_SERVERS_IN_ONE_CHASSIS 4 -PERIODIC_LOG_INTERVAL ${LOG_INTERVAL} -SCHEDULING_ALGORITHM best_edp -DVFS_SETTING ${DVFS} 1> ${OUTPUT_DIR}/LLNL/${DVFS}.o 2> ${OUTPUT_DIR}/LLNL/${DVFS}.e
	echo "SDSC with DVFS ${DVFS}"
	date
	./SimWare ${WORKLOADS}/SDSC-SP2-short.swf -NUMBER_OF_CORES_IN_ONE_SERVER 1 -NUMBER_OF_SERVERS_IN_ONE_CHASSIS 2 -PERIODIC_LOG_INTERVAL ${LOG_INTERVAL} -SCHEDULING_ALGORITHM best_edp -DVFS_SETTING ${DVFS} 1> ${OUTPUT_DIR}/SDSC/${DVFS}.o 2> ${OUTPUT_DIR}/SDSC/${DVFS}.e
done
